# This is the backing data for everything
# SQL is used as long-term storage
# You may choose to use MySQL or SQLite
# An SQL database of SOME description is required
sql:
  # The type of database to use. May be either MySQL or SQLite
  type: 'sqlite'
  # Number of connections to use. Cannot be lower than 1
  # Recommended 2+ for parallel queries
  threads: 2
  # Table prefix, optional
  # This will allow multiple Spruce installations to go to the same database without conflicting
  prefix: ''
  mysql:
    address: '127.0.0.1'
    port: 3306
    user: ''
    pass: ''
    database: 'spruce'
  sqlite:
    file: 'spruce.db'

# Specify what types of data to log
log:
  player:
    chat: true # Player chat/talk
    command: true # Player commands
    login: true # Player login/join
    logout: true # Player logout/quit
    worldChange: true # Player changes worlds
  entity:
    death: true # Entity deaths
    inventoryChange: true # Entity inventory changes
    spawn: false # Entity spawns, does not track items
    worldChange: false # Entity world changes
  block:
    # Low frequency/intensity
    player: true # Block changes from players
    explode: true # Blocks removed by explosion
    sign: true # Sign text changes
    ignite: true # Block being lit on fire
    # Recommended bare-minimum
    grow: true # Crop growth
    burn: true # Block burning up in a fire
    inventory: true # Block inventory changes
    entity: true # Block changes from entities (not players)
    piston: true # Piston changes and block movements from pistons
    # High frequency/intensity
    teleport: false # Teleporting blocks or blocks that flow
    damage: false # Block damage such as anvils, etc
    dispense: false # Block dispensing an item from its inventory
    form: false # Snow/Ice melting or forming, cobble/obsidian forming, fire burning out, etc
    spread: false # Muscrooms, fire, grass spreading, etc
    cauldron: false # Cauldron water level change
    decay: false # Leaf decay
    # Plugins
    worldedit: true # WorldEdit/AsyncWorldEdit/FastAsyncWorldEdit/etc

# Logs/data beyond these values will be automatically removed from the database
autoPurge:
  # Player chat/commands/logins/logouts/world changes
  player: 30days
  # Entity/block/WorldEdit data
  world: 7days